config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get '/playlists/find_new_playlists', to: 'playlists#find_new_playlists', as: 'find_new_playlists'
  get '/playlists/find_popular_playlists', to: 'playlists#find_popular_playlists', as: 'find_popular_playlists'
  get '/playlists/add_new_spotify_playlist', to: 'playlists#new_spotify_playlist', as: 'add_spotify_playlist'
  post '/playlists/add_new_spotify_playlist', to: 'playlists#add_spotify_playlist'
  get '/playlists/:pid/songs/new', to: 'songs#new', as: 'new_song'
  get '/playlists/:pid/songs/:sid/edit', to: 'songs#edit', as: 'edit_song'
  delete '/playlists/:pid/songs/:sid/remove', to: 'playlist_songs#destroy', as: 'destroy_song_add'
  patch '/playlists/:pid/songs/:sid', to: 'songs#update'
  delete '/playlists/:pid/songs/:sid/destroy', to: 'songs#destroy', as: 'destroy_song'
  get '/playlists/:pid/songs/:sid', to: 'songs#show', as: 'song'
  get '/playlists/:pid/songs', to: 'songs#index', as: "songs"
  post '/playlists/:pid/songs', to: 'songs#create'
  post '/playlists/:pid/follows/create', to: 'follows#create', as: "new_follow"
  delete '/playlists/:pid/follows/destroy', to: 'follows#destroy', as: "destroy_follow"
  resources :playlists
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :follows, dependent: :destroy
  has_many :playlists, through: :follows
  has_many :comments, dependent: :destroy
  validates :dj_name, uniqueness: true
  has_secure_password

  def songs
    self.playlists.map do |playlist|
      playlist.songs
    end.flatten
  end

  def spotify_playlist_creator(spotify_data)
    playlist = self.playlists.create(name: spotify_data.name, description: spotify_data.description, url: spotify_data.open_url)
    spotify_data.tracks_to_hash_array.each do |hash|
      song = Song.all.find_by(name: hash[:title], artist: hash[:artist])
      if song
        PlaylistSong.create(playlist_id: playlist.id, song_id: song.id)
      else
        #playlist.songs.create(name: hash[:title], artist: hash[:artist], year: hash[:year])
        playlist.songs.create(hash)
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    if @user.id != current_user.id
      redirect_to "/users/#{current_user.id}"
    else
      render :show
    end
  end

  def new
    if !!current_user
      redirect_to playlists_path
    else
      @errors = flash[:errors]
      @user = User.new
      render :new
    end
  end

  def edit
    if @user.id != current_user.id
      redirect_to "/users/#{current_user.id}/edit"
    else
      render :edit
    end
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to :controller => "playlists", :action => "index"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:dj_name, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dj_name %>
    <%= form.text_field :dj_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', playlists_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Dj name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.dj_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%# <link href="signin.css" rel="stylesheet"> %>

<div class="transparent login-container">

<img src="<%=image_url('logo.png')%>">

<h1>Signup!</h1><br>

<% if @errors %>
  <% @errors.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%# <%= render 'form', user: @user %>

<%# <%= link_to 'Back', users_path %>



<%= form_for @user, :html => {:class => "form-signin"} do |f| %>
<%= f.label :dj_name %><br>
<%= f.text_field :dj_name %><br><br>
<%= f.label :password %><br>
<%= f.text_field :password %><br><br>
<%= f.submit %><br><br>
<% end %>
<p>Already have an account? <%= link_to "Sign in", login_path %></p>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dj name:</strong>
  <%= @user.dj_name %>
</p>

<% if current_user.id == @user.id %>
<%= button_to 'Delete Account', user_path(@user), method: :delete, data:{confirm: 'Are you sure you would like 
to delete this account?'} %>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>