config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get '/playlists/find_new_playlists', to: 'playlists#find_new_playlists', as: 'find_new_playlists'
  get '/playlists/find_popular_playlists', to: 'playlists#find_popular_playlists', as: 'find_popular_playlists'
  get '/playlists/add_new_spotify_playlist', to: 'playlists#new_spotify_playlist', as: 'add_spotify_playlist'
  post '/playlists/add_new_spotify_playlist', to: 'playlists#add_spotify_playlist'
  get '/playlists/:pid/songs/new', to: 'songs#new', as: 'new_song'
  get '/playlists/:pid/songs/:sid/edit', to: 'songs#edit', as: 'edit_song'
  delete '/playlists/:pid/songs/:sid/remove', to: 'playlist_songs#destroy', as: 'destroy_song_add'
  patch '/playlists/:pid/songs/:sid', to: 'songs#update'
  delete '/playlists/:pid/songs/:sid/destroy', to: 'songs#destroy', as: 'destroy_song'
  get '/playlists/:pid/songs/:sid', to: 'songs#show', as: 'song'
  get '/playlists/:pid/songs', to: 'songs#index', as: "songs"
  post '/playlists/:pid/songs', to: 'songs#create'
  post '/playlists/:pid/follows/create', to: 'follows#create', as: "new_follow"
  delete '/playlists/:pid/follows/destroy', to: 'follows#destroy', as: "destroy_follow"
  resources :playlists
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :playlist_songs, dependent: :destroy
  has_many :playlists, through: :playlist_songs
  validates :artist, presence: true
  validates :name, presence: true

  def new_lyrics
    if self.artist && self.name
      begin
        url = URI.escape("https://api.lyrics.ovh/v1/#{self.artist.downcase}/#{self.name.downcase}")
        response = RestClient.get url
      rescue RestClient::ExceptionWithResponse => e
        if e.class == RestClient::NotFound
          "I'm sorry, it looks like we don't have lyrics available for #{self.artist}'s #{self.name}'"
        end
      end
      if response
        JSON.parse(response)["lyrics"]
      end
    else
      "This program needs both a song name and a song title to render its lyrics."
    end
  end

  def self.find_song(artist:, name:, playlist:)
    Song.find_by(name: name, artist: artist)
  end

  def self.create_song(artist:, name:, playlist:)
    song = playlist.songs.new(artist: artist, name: name)
    if song.valid?
      song.create_song_on_spotify(playlist)
    end
  end

  def create_song_on_spotify(playlist)
    song_data = SongImporter.new(name: self.name, artist: self.artist)
    song_data_hash = song_data.song_data_to_hash
    if song_data_hash
      playlist.songs.create(song_data_hash)
    end
  end

  def self.find_or_create_song(artist:, name:, playlist:)
    song = self.find_song(artist: artist, name: name, playlist: playlist)
    if song.class == Song
      PlaylistSong.create(playlist_id: playlist.id, song_id: song.id)
      song
    else
      self.create_song(artist: artist, name: name, playlist: playlist)
    end
  end


  def self.sort_by_popularity
    self.all.sort_by do |song|
      song.playlists.length
    end.reverse
  end

  def self.top_x_songs(x)
    songs = Song.sort_by_popularity[0..x]
    songs.map do |song|
      [song.name, song.artist, song.playlists.length]
    end
  end
  #Spotify API Stuff




end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]



  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @song_arrays = Song.top_x_songs(5)
    @error = flash[:error]
    flash[:playlist_id] = params[:pid]
    # byebug
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json

  def create
    @playlist = Playlist.find(flash[:playlist_id])
    song = Song.find_or_create_song(artist: song_params[:artist], name: song_params[:name], playlist: @playlist)
    if song.class == Song
      redirect_to @playlist
    else
      flash[:playlist_id] = flash[:playlist_id]
      flash[:error] = "#{song_params[:name]} by #{song_params[:artist]} was not found on spotify"
      send_back_to_new_song
    end
  end
  # def create
  #   @playlist = Playlist.find(flash[:playlist_id])
  #   @song = Song.find_by(name: song_params[:name], artist: song_params[:artist])
  #   if @song
  #     PlaylistSong.create(playlist_id: @playlist.id, song_id: @song.id)
  #     redirect_to @playlist
  #   else
  #     @songdata = SongImporter.new(name: song_params[:name], artist: song_params[:artist])
  #     if @songdata.import_data.length > 0
  #       @songdatahash = @songdata.song_data_to_hash
  #       if @songdatahash
  #         @song = @playlist.songs.create(@songdatahash)
  #         if @song.valid?
  #           redirect_to @playlist
  #         else
  #           flash[:errors] = @song.errors
  #           send_back_to_new_song
  #         end
  #       else
  #         flash[:errors] = ["There is no song named #{song_params[:name]} by #{song_params[:artist]} on Spotify."]
  #         send_back_to_new_song
  #       end
  #     else
  #       flash[:errors] = @song.errors
  #       send_back_to_new_song
  #     end
  #   end
  # end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:sid])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist)
    end

    def send_back_to_new_song
      redirect_to new_song_path(playlist_id: @playlist.id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<% if @error %>
  <%= @error %><br>
<% end %>
<%= form_for @song do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>
  <%= f.label :artist %>
  <%= f.text_field :artist %><br><br>
  <%= f.submit %>
  <br>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to "Back to #{@song.name} Details", song_path(pid: params[:pid], sid: @song.id) %>
<%= link_to 'Back to Playlist', playlist_path(params[:pid]) %>

app/views/songs/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Genre</th>
      <th>Lyrics</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.artist %></td>
        <td><%= song.genre %></td>
        <td><%= song.lyrics %></td>
        <td><%= song.year %></td>
        <td><%= link_to 'Show', song_path(pid: , sid: song.id) %></td>
        <td><%= link_to 'Edit', edit_song_path(sid: song.id) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>
-->

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<br>
<h3>Top Songs</h3>
<div class="transparent">
<% i = 0 %>
<% @song_arrays.each do |song_array| %>
  <% i +=1 %>
  <%= "#{i} -- #{song_array[0]} -- #{song_array[1]} (Number of playlists: #{song_array[2]})" %>
  <br>
<% end %>
</div>

<%= link_to 'Back', playlist_path(flash[:playlist_id]) %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Year:</strong>
  <%= @song.year %>
</p>

<% if @song.url %>
<iframe src="<%= @song.url.split(".com/").join(".com/embed/") %>" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
<% end %>
<p>
  <strong>Lyrics:</strong>
  <%= simple_format(@song.new_lyrics) %>
</p>




<%= link_to 'Edit', edit_song_path(sid: params[:sid], pid: params[:pid]) %> |
<%= link_to 'Back', playlist_path(params[:pid]) %>