config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get '/playlists/find_new_playlists', to: 'playlists#find_new_playlists', as: 'find_new_playlists'
  get '/playlists/find_popular_playlists', to: 'playlists#find_popular_playlists', as: 'find_popular_playlists'
  get '/playlists/add_new_spotify_playlist', to: 'playlists#new_spotify_playlist', as: 'add_spotify_playlist'
  post '/playlists/add_new_spotify_playlist', to: 'playlists#add_spotify_playlist'
  get '/playlists/:pid/songs/new', to: 'songs#new', as: 'new_song'
  get '/playlists/:pid/songs/:sid/edit', to: 'songs#edit', as: 'edit_song'
  delete '/playlists/:pid/songs/:sid/remove', to: 'playlist_songs#destroy', as: 'destroy_song_add'
  patch '/playlists/:pid/songs/:sid', to: 'songs#update'
  delete '/playlists/:pid/songs/:sid/destroy', to: 'songs#destroy', as: 'destroy_song'
  get '/playlists/:pid/songs/:sid', to: 'songs#show', as: 'song'
  get '/playlists/:pid/songs', to: 'songs#index', as: "songs"
  post '/playlists/:pid/songs', to: 'songs#create'
  post '/playlists/:pid/follows/create', to: 'follows#create', as: "new_follow"
  delete '/playlists/:pid/follows/destroy', to: 'follows#destroy', as: "destroy_follow"
  resources :playlists
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :follows, dependent: :destroy
  has_many :users, through: :follows
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs


  def original_author
    User.find(Follow.all.where(playlist_id: self.id).order(:created_at).first.user_id)
  end

  def original_author_dj_name
    self.original_author.dj_name
  end

  def does_user_follow?(current_user)
    !!self.follows.find_by(user_id: current_user.id)
  end

  def permission_to_edit?(current_user)
    self.original_author == current_user
  end

  def permission_to_delete?(current_user)
    self.original_author == current_user
  end

  def song_for_image
    self.songs.find do |song|
      song.image_url
    end
  end

  def self.sort_by_popularity
    self.all.sort_by do |playlist|
      playlist.follows.length
    end.reverse
  end

  def top_x_playlists(x)
    self.sort_by_popularity[0..x].map do |playlist|
      [playlist.name, playlist.original_author_dj_name, playlist.follows.length]
    end
  end
end

  # def image
  #   song = self.song_for_image
  #   if song
  #     song.image_url
  #   else
  #     image_url('logo.png')
  #   end
  # end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  def index
    @playlists = current_user.playlists
  end

  def find_new_playlists
    @playlists = Playlist.all
    render :find_new_playlists
  end

  def find_popular_playlists
    @playlists = Playlist.all.sort_by_popularity[0..14]
    render :most_popular_playlists
  end


  def new_spotify_playlist
    @error = flash[:error]
    render :spotify_new
  end

  def add_spotify_playlist
    if (params[:url]).class == String && (params[:url]).length >0 && (params[:url]).index("/")
      begin
        spotify_data = PlaylistImporter.new(params[:url])
      rescue RestClient::ExceptionWithResponse => e
      end
      if spotify_data
        current_user.spotify_playlist_creator(spotify_data)
        redirect_to playlists_path
      else
        flash[:error] = "Error: Invalid Playlist Link"
        redirect_to add_spotify_playlist_path
      end
    else
      flash[:error] = "Error: Please add a valid link."
      redirect_to add_spotify_playlist_path
    end
  end

  def show
    @songs = @playlist.songs
    @permission = @playlist.permission_to_edit?(current_user) && @playlist.permission_to_delete?(current_user)
  end

  def new
    @users = User.all
    @playlist = Playlist.new
    render :new
  end

  def edit
    if current_user == @playlist.original_author
      render :edit
    else
      redirect_to playlists_path
    end
  end

  def create
    @playlist = current_user.playlists.create(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      @errors = @playlist.errors.full_messages
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:name, :description, :author_id)
    end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>
  <%= f.label :description %>
  <%= f.text_area :description %><br><br>
  <%= f.submit %>
  <br>
<% end %>

app/views/playlists/_playlists_render.erb
<div class="container">
<div class="row text-center" style="display:flex; flex-wrap: wrap; justify-content: space-between;">
<% @playlists.each do |playlist| %>
<div class="col-md-4 col-sm-6 card text-white bg-dark border-warning" >
  <a href="<%= playlist_path(playlist) %>"><img class="card-img-top" src="<%=playlist.song_for_image ? playlist.song_for_image.image_url : image_url('logo.png')%>" alt="<%=playlist.song_for_image ? "#{playlist.song_for_image.album} Cover" : "Codechella Logo" %>"></a>
  <div class="card-body text-white">
    <h5 class="card-title playlist_name "><%= link_to playlist.name, playlist %></h5>
    <h6 class="card-subtitle mb-2 "> <%= playlist.original_author_dj_name %></h6>
    <p class="card-text"><%= playlist.description %></p>
    <p class="card-text">Number of Follows: <%= playlist.follows.length %></p>
    <% if playlist.original_author == current_user %>
    <div class= "your_playlist">This is your playlist</div>
    <% elsif playlist.does_user_follow?(current_user) %>
    <form action="<%= destroy_follow_path(:pid => playlist.id) %>" method="post">
    <input name="_method" type="hidden" value="delete" />
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button class="btn btn-primary" type="submit">Unfollow this Playlist</button>
    </form>
    <% else %>
    <form action="<%= new_follow_path(:pid => playlist.id) %>" method="post">
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button class="btn btn-primary" type="submit">Follow this Playlist</button>
    </form>
    <% end %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form'%>

<%= link_to 'Show', @playlist %> 
<%= link_to 'Back', @playlist %>

app/views/playlists/find_new_playlists.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color: white">Playlists</h1>

<%= button_to 'New Playlist', new_playlist_path, :method => 'get', :class => "btn btn-secondary btn-lg" %>
<br>
<%= render 'playlists_render'%>

<br>

app/views/playlists/index.html.erb
<h1 style="color: white">Playlists</h1>

<%# make these into buttons %>
<div class="new_playlists">
<%= button_to 'New Playlist', new_playlist_path, :method => 'get', :class => "btn btn-secondary btn-lg" %>
<%= button_to 'Add from Spotify', add_spotify_playlist_path, :method => 'get', :class => "btn btn-secondary btn-lg" %>
</div>

<% if @playlists.size >0 %>

<%= render 'playlists_render'%>

<% else %>
  <h3>You're not following any playlists<br><br>Find or create a playlist<br><br> or hit up the feed to see what's being shared</h3>

<% end %>
<br>

app/views/playlists/most_popular_playlists.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color: white">Most Popular Playlists</h1>

<%= button_to 'New Playlist', new_playlist_path, :method => 'get', :class => "btn btn-secondary btn-lg" %>
<br>
<%= render 'playlists_render'%>

<br>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<div class="container">

  <h1><%= @playlist.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @playlist.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @playlist.original_author_dj_name %>
</p>

<% if @playlist.url %>
<iframe src="<%= "https://open.spotify.com/embed/playlist/"+@playlist.url.split("/").last%>" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
<% end %>
<br><br>
<% if @permission%>
  <% if @playlist.url %>
  <%= link_to 'Add Song to Playlist (Will not update embedded web player)', new_song_path(pid: @playlist.id) %> |
  <% else %>
  <%= link_to 'Add Song to Playlist', new_song_path(pid: @playlist.id) %> |
  <% end %>
<%= link_to 'Edit Playlist Properties', edit_playlist_path(pid: @playlist.id) %> |
<%= link_to 'Destroy', @playlist, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% else %>
<% end %>
<%= link_to 'Back', playlists_path %>


<% if @songs.length > 0 %>
<div class="container">
<div class="transparent">
<h2>Songs</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.name, "/playlists/#{@playlist.id}/songs/#{song.id}"  %></td>
        <td><%= song.artist %></td>
        <% if @permission%>
        <td><%= link_to 'Remove from Playlist', "/playlists/#{@playlist.id}/songs/#{song.id}/remove", method: :delete %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<h2>This playlist has no songs on it. </h2>

<% end %>
</div>
</div>
</div>

app/views/playlists/spotify_new.erb
<div class="container">

<br>
<% if @error %>
  <%= @error %>
<% end %><br>

<h3>Spotify Playlist Link:</h3>
<form class="url" id="url" action="/playlists/add_new_spotify_playlist" accept-charset="UTF-8" method="post">
  <%= token_tag %>
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
<div class="input-group">
  <div class="input-group-prepend">
    <input class="btn btn-outline-secondary bg-danger text-white" type="submit" value="Enter Spotify Link">
  </div>
  <input class="form-control" aria-label="Enter Spotify Playlist Link" name="url" id="url">
</div>
</form>

<br><br>
<h4>Copy your playlist link from spotify.<br>Importing a long playlist may take a little while.<br>If it's loading, it's working.</h4>
</div>